version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    container_name: redis-nestjs-socket

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongo-nestjs-socket

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongodb
